import { Geist, Geist_Mono, Work_Sans, EB_Garamond, Fraunces, Archivo, Syne } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import NavStandard from "./components/layout/NavStandard";
import Footer from "./components/layout/Footer";
import FooterElegant from "./components/layout/FooterElegant";
import NavigationMenuComponent from "./components/layout/NavigationMenu";





const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
})

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
})

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
})

export const metadata = {
  title: "Susan Albertsen Psykoterapi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">


      {/* Standard header */}
      <body
        className={`${fraunces.variable} ${archivo.variable} ${syne.variable} antialiased`}
      >

        <NavigationMenuComponent />
        <main >
          {children}


        </main>
        <FooterElegant />

      </body>
    </html>
  );
}
